---
title: "R hodina 2023-04-13 (Tabulky)"
output: html_notebook
---
#### Vyčistění paměti
```{r}
rm(list=ls()) # smaz vsechny promenne
print(ls())
library(ggplot2)
library(dplyr)
library(tidyr)
```


```{r}
  scatter.smooth(iris$Sepal.Length, iris$Sepal.Length, xlab="x", ylab="y")
```
```{r}
names <- c("Petal" , "Sepal")
valls <- c(mean(iris$Petal.Length),mean(iris$Sepal.Length))

mydata <- data.frame(names, valls)

mplot <- ggplot(mydata, aes(x=names,y=valls,fill=names)) + geom_bar(stat="identity") 
mplot + scale_y_continuous(breaks = seq(0,6,0.25)) + coord_fixed(ratio = 1/1.5)

```
```{r}
names <- c("Petal" , "Sepal")
valls <- c(mean(iris$Petal.Length),mean(iris$Sepal.Length))

mydata <- data.frame(names, valls)

mplot <- ggplot(mydata, aes(x=names,y=valls,fill=names)) + geom_bar(stat="identity") 
mplot + scale_y_continuous(breaks = seq(0,6,0.25)) + coord_fixed(ratio = 1/1.5) + coord_polar("y")

```
```{r}
pressure

iris %>% ggplot(aes(x=Species,y=Petal.Length)) + geom_boxplot()

df <- read.csv("./StudentsPerformance.csv")
```